import { describe, it, expect } from 'vitest';
import { WriterAgent } from '../../../src/agents/writer/writer.agent';
import { MockLanguageModel } from '../../../src/llm/mock-llm';
import { WritingBrief } from '../../../src/types/writer.types';

describe('WriterAgent', () => {
  it('drafts complete technical document with numbered citations and auto-review', async () => {
    const writer = new WriterAgent({
      verbose: false,
      autoReview: true,
      maxRevisionPasses: 1,
    });

    const thoughts: string[] = [];
    const steps: string[] = [];
    writer.on('thought', (e) => { thoughts.push(e.data.message); });
    writer.on('step_start', (e) => { steps.push(e.data.step); });

    const brief: WritingBrief = {
      topic: 'Scalable Micro-Agent Architecture for Enterprise AI',
      targetAudience: 'technical',
      format: 'article',
      tone: 'authoritative',
      citationStyle: 'numbered',
      minWords: 400,
      maxWords: 800,
      keyPointsToCover: [
        'State machine orchestration',
        'Failure isolation boundaries',
        'Latency reduction in multi-turn tool calling',
      ],
    };

    const result = await writer.execute(brief);

    expect(result).toBeDefined();
    expect(result.id.startsWith('written-doc-')).toBe(true);
    expect(result.draft.title).toContain('Scalable Micro-Agent Architecture');
    expect(result.draft.sections.length).toBeGreaterThanOrEqual(3);
    expect(result.draft.totalWordCount).toBeGreaterThan(100);
    expect(result.finalMarkdown).toContain('# Scalable Micro-Agent Architecture');
    expect(result.finalMarkdown).toContain('## References & Source Citations');
    expect(result.review).toBeDefined();
    expect(result.review!.overallScore).toBeGreaterThanOrEqual(70);
    expect(result.review!.sectionCritiques.length).toBe(result.draft.sections.length);

    expect(thoughts.length).toBeGreaterThan(0);
    expect(steps).toContain('outline_generation');
    expect(steps).toContain('section_drafting');
    expect(steps).toContain('review_and_critique');
    expect(writer.status).toBe('completed');
  });

  it('supports alternative citation styles: footnote and author_date', async () => {
    const footnoteWriter = new WriterAgent();
    const footnoteResult = await footnoteWriter.execute({
      topic: 'Agent Reliability',
      citationStyle: 'footnote',
    });
    expect(footnoteResult.finalMarkdown).toContain('[^1]');

    const authorDateWriter = new WriterAgent();
    const authorDateResult = await authorDateWriter.execute({
      topic: 'Agent Reliability',
      citationStyle: 'author_date',
    });
    expect(authorDateResult.finalMarkdown).toContain('(Industry, 2024)');
    expect(authorDateResult.finalMarkdown).toContain('**Industry Consortium (2024)**');
  });

  it('supports custom outline and skips LLM outline generation', async () => {
    const customOutline = {
      title: 'Custom Blueprint',
      targetWordCount: 500,
      sections: [
        {
          sectionId: 'sec-custom-1',
          heading: 'Core Foundational Logic',
          level: 2,
          description: 'Deep dive into foundation logic',
          targetWords: 250,
          keyPoints: ['Point A', 'Point B'],
          sourceCitations: ['1'],
        },
      ],
    };

    const writer = new WriterAgent({ customOutline });
    const res = await writer.execute({ topic: 'Custom Topic' });

    expect(res.draft.title).toBe('Custom Blueprint');
    expect(res.draft.sections.length).toBe(1);
    expect(res.draft.sections[0].heading).toBe('Core Foundational Logic');
  });

  it('integrates with LLM for outline, drafting, critique, and revision', async () => {
    const mockLlm = new MockLanguageModel();

    // Outline response
    mockLlm.queueResponse(JSON.stringify({
      title: 'LLM Guided Title',
      subtitle: 'LLM Subtitle',
      targetWordCount: 600,
      sections: [
        {
          sectionId: 'sec-1',
          heading: 'LLM Generated Section 1',
          level: 2,
          description: 'Description 1',
          targetWords: 300,
          keyPoints: ['Key Alpha'],
          sourceCitations: ['1'],
        },
      ],
    }));

    // Section drafting response
    mockLlm.queueResponse('This is high caliber technical prose generated by LLM for Section 1 with deep insights and analysis.');

    // Review critique response (overall score 80 to trigger revision pass)
    mockLlm.queueResponse(JSON.stringify({
      overallScore: 80,
      readabilityScore: 82,
      coherenceScore: 85,
      toneAlignmentScore: 88,
      factualAccuracyScore: 85,
      suggestedImprovements: ['Enhance quantitative depth'],
      sectionCritiques: [
        {
          sectionId: 'sec-1',
          heading: 'LLM Generated Section 1',
          critique: 'Good, but needs more quantitative rigor.',
          suggestions: ['Add metric analysis'],
          wordCountScore: 85,
          flowScore: 85,
        },
      ],
    }));

    // Revision pass response
    mockLlm.queueResponse('Revised prose: This is refined, highly polished technical prose incorporating thorough quantitative metrics and empirical proofs.');

    const writer = new WriterAgent({
      model: mockLlm,
      maxRevisionPasses: 1,
      autoReview: true,
    });

    const result = await writer.execute({
      topic: 'Next-Gen LLM Agents',
    });

    expect(result.draft.title).toBe('LLM Guided Title');
    expect(result.revisionCount).toBe(1);
    expect(result.draft.sections[0].body).toContain('Revised prose');
    expect(writer.metrics.llmCallCount).toBe(4);
    expect(writer.metrics.totalTokensUsed).toBeGreaterThan(0);
  });

  it('handles execution cancellation', async () => {
    const writer = new WriterAgent();
    const abortController = new AbortController();

    const promise = writer.execute(
      { topic: 'Cancelled writing job' },
      { contextId: 'cancel-writer-ctx', startTime: Date.now(), signal: abortController.signal }
    );

    abortController.abort();
    await expect(promise).rejects.toThrow('Execution aborted');
    expect(writer.status).toBe('failed');
  });
});
